# Generated by Django 4.2.5 on 2024-02-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescription.medication')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField()),
                ('date_prescribed', models.DateField(auto_now_add=True)),
                ('medications', models.ManyToManyField(through='Prescription.PrescribedMedication', to='Prescription.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
        migrations.AddField(
            model_name='prescribedmedication',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescription.prescription'),
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dosage', models.CharField(max_length=100)),
                ('refills_taken', models.IntegerField(default=0)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prescription.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
