# Generated by Django 4.2.5 on 2024-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='days_of_week',
            field=models.ManyToManyField(related_name='doctor_availabilities', to='Doctor.weekday'),
        ),
    ]
