# Generated by Django 4.2.5 on 2024-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_weekday_remove_doctoravailability_day_of_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='days_of_week',
            new_name='day_of_week',
        ),
    ]
